server:
  port: 8080
  max-http-header-size: 16384

spring:

  application:
    name: todo-api-gateway

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 5000ms

  redis:
    host: localhost
    port: 6379

  cache:
    type: redis
    redis:
      time-to-live: 60000

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

  datasource:
    url: jdbc:sqlite:todo.db
    driver-class-name: org.sqlite.JDBC
    username:
    password:

    jpa:
      hibernate:
        ddl-auto: create-drop
      show-sql: true
      properties:
        hibernate:
          format_sql: true

jackson:
  serialization:
    write-dates-as-timestamps: false
    write-date-timestamps-as-nanoseconds: false
  deserialization:
    read-date-timestamps-as-nanoseconds: false
  date-format: yyyy-MM-dd HH:mm:ss
  time-zone: UTC

logging:
  level:
    org.example: DEBUG
    org.springframework.cache: TRACE
    org.springframework.data.redis: DEBUG